export const WS_ORDER_CONNECTION_START: "WS_ORDER_CONNECTION_START" = "WS_ORDER_CONNECTION_START";
export const WS_ORDER_CONNECTION_SUCCESS: 'WS_ORDER_CONNECTION_SUCCESS' = 'WS_ORDER_CONNECTION_SUCCESS';
export const WS_ORDER_CONNECTION_ERROR: 'WS_ORDER_CONNECTION_ERROR' = 'WS_ORDER_CONNECTION_ERROR';
export const WS_ORDER_CONNECTION_CLOSED: 'WS_ORDER_CONNECTION_CLOSED' = 'WS_ORDER_CONNECTION_CLOSED';
export const WS_ORDER_GET_MESSAGE: 'WS_ORDER_GET_MESSAGE' = 'WS_ORDER_GET_MESSAGE';

export const WS_USER_ORDER_CONNECTION_START: "WS_USER_ORDER_CONNECTION_START" = "WS_USER_ORDER_CONNECTION_START";
export const WS_USER_ORDER_CONNECTION_SUCCESS: 'WS_USER_ORDER_CONNECTION_SUCCESS' = 'WS_USER_ORDER_CONNECTION_SUCCESS';
export const WS_USER_ORDER_CONNECTION_ERROR: 'WS_USER_ORDER_CONNECTION_ERROR' = 'WS_USER_ORDER_CONNECTION_ERROR';
export const WS_USER_ORDER_CONNECTION_CLOSED: 'WS_USER_ORDER_CONNECTION_CLOSED' = 'WS_USER_ORDER_CONNECTION_CLOSED';
export const WS_USER_ORDER_GET_MESSAGE: 'WS_USER_ORDER_GET_MESSAGE' = 'WS_USER_ORDER_GET_MESSAGE';